server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: wete2808
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
ead:
  api:
    url:
      authuser: 'http://EAD-COURSE-SERVICE/ead-authuser'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
